### PR TITLE
[merged] .redhat-ci.yml: new file

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@rh-atomic-bot r+ e7e22ec

**Comment by cgwalters** [comment]
@rh-atomic-bot r+ e7e22ec

**Comment by jlebon** [comment]
Hmm, something wrong with homu. It's not pushing to the auto branch.
@giuseppe also, if you want to make use of homu, you'll have to add:

```yaml
branches:
  - master
  - auto
  - try
```

so that when homu kicks in, the auto branch gets tested.

**Comment by giuseppe** [comment]
@jlebon added a fixup patch here :arrow_up:

**Comment by cgwalters** [comment]
@rh-atomic-bot r+  	c39c16b

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
