### PR TITLE
Support new bwrap features

### PR DESCRIPTION
**Pull request by giuseppe**
A bunch of patches to add support for these new features in bubblewrap,

Add support for: capabilities, as-pid-1, additional UIDs/GIDs mappings

https://github.com/projectatomic/bubblewrap/pull/101
https://github.com/projectatomic/bubblewrap/pull/196

### CODE REVIEW

**Comment by giuseppe** [comment]
I needed to add a patch to address changes in the OCI specs and how seccomp is passed.  Now tests are passing, so drop the WIP tag

**Comment by giuseppe** [comment]
I've created a demo here to show how it works:

https://asciinema.org/a/FyPoslnrGxbWy1mE1GgAanLzf

**Comment by giuseppe** [comment]
ping @rhatdan

**Comment by alexlarsson** [comment]
Blog or gtfo!

**Comment by giuseppe** [comment]
:D ok I will blog about it

**Comment by giuseppe** [comment]
@rh-atomic-bot delegate=yuqi-zhang

**Comment by yuqi-zhang** [comment]
Basic functionality looks good, put probably needs more extensive testing. Great work! Merging for now.

@rh-atomic-bot r+ faf55d9

**Pull request closed without merging**
